from Orbaplaw.NaturalBondOrbitalMethods import NaturalAtomicOrbital
from Orbaplaw.NaturalBondOrbitalMethods import NaturalBondOrbital
from Orbaplaw.NaturalBondOrbitalMethods import OptNaturalBondOrbital
from Orbaplaw.NaturalBondOrbitalMethods import PrincipalInteractingOrbital

generateNaturalAtomicOrbital=NaturalAtomicOrbital.generateNaturalAtomicOrbital
NaturalAtomicOrbital=NaturalAtomicOrbital.NaturalAtomicOrbital

generateNaturalBondOrbital=NaturalBondOrbital.generateNaturalBondOrbital
NaturalBondOrbital=NaturalBondOrbital.NaturalBondOrbital

generateOptNaturalBondOrbital=OptNaturalBondOrbital.generateOptNaturalBondOrbital
OptNaturalBondOrbital=OptNaturalBondOrbital.OptNaturalBondOrbital

generatePrincipalInteractingOrbital=PrincipalInteractingOrbital.generatePrincipalInteractingOrbital
PrincipalInteractingOrbital=PrincipalInteractingOrbital.PrincipalInteractingOrbital
