from Orbaplaw.NaturalBondOrbitalMethods import NaturalAtomicOrbital
from Orbaplaw.NaturalBondOrbitalMethods import NaturalBondOrbital

generateNaturalAtomicOrbital=NaturalAtomicOrbital.generateNaturalAtomicOrbital
NaturalAtomicOrbital=NaturalAtomicOrbital.NaturalAtomicOrbital
generateNaturalBondOrbital=NaturalBondOrbital.generateNaturalBondOrbital
NaturalBondOrbital=NaturalBondOrbital.NaturalBondOrbital
